### ISSUE TITLE
gibberish being read in libuart 3.0.2rc2

### ISSUE THREAD

**Issue by sprajagopal** [xmos/lib_uart#4]
I tried the following test code with libuart 3.0.2 rc2 (only the main parallel assignment is shown, as the functions are all library functions):

```
par
{

    on tile[0]:
    {
        par {

      input_gpio_1bit_with_events(i_gpio_rx[0], rx_fw);
      uart_rx(uif[0], null, 16, 115200, UART_PARITY_NONE, 8, 1, i_gpio_rx[0]);
      uart_tx_buffered(utif[0], null, 50, 115200, UART_PARITY_NONE, 8, 1, i_gpio_tx_world[0]);
      output_gpio(i_gpio_tx_world, 1, tx_ack, null);

    }

    on tile[1]:
    {
        par{

    {
      while(1){
        unsigned char ch = uif[0].wait_for_data_and_read();
        utif[0].write(ch);
      }
     }
   }
 }
}
```

When I send something on the rx_fw pin, I expect the same reply on tx_ack. I am testing with a ttl-usb converter and a serial terminal.
I find that when the hex string is short (<3 bytes), the reply is identical. Anything longer and the reply gets garbled after 3 bytes. 
Any clues?

Could be a related post. Is the timing going off? 
[link to xcore forum post](http://www.xcore.com/forum/viewtopic.php?p=2375#p2375)

EDIT:
I found the following things in the code:
   (a) since the library uses combinable functions, it doesn't use ordering for its select cases. For a test, I removed the combinable keyword and introduced ordering to the select cases. The result: for 100 byte hex strings, 1-2 bytes are garbled in the middle but that's all. Earlier, only the first few bytes were properly read. 

I think this has something to do with the code structuring rather than the external setup.

**Comment by pthedinger** [comment]
Looking at this, there is no test for this case. I have written a test, but find that it all works fine. Our TX code seems to have a 0.5% drift on the clock. That should not cause your receiver to have issues after such a small number of characters. However, this reduced transmit rate means that it is not possible to receive at line rate and re-transmit it. I will look at fixing this in the buffered transmitter.
